server:
  address: localhost
  port: 8090

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3308/ta
      username: the2792
      password: canyou12
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE